theme: jekyll-theme-minimal
title: Jose Luis Gonzalez
description: M.S. Statistics
logo: assests/img/profile.png
author: 
  name      : Jose Luis Gonzalez
  bio       : M.S. Statistics Porfolio
  location  : Greater Los Angeles Area
  url       : joselgonzalez271@gmail.com


social-links:
  linkedin      : jose-gonzalez-0b4961183
  github        : JoseGonzalezStatistics
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
